import Config from "react-native-config";

export const EnvironmentConfiguration = {
    ENVIRONMENT: Config.ENVIRONMENT,
    API_URL: Config.API_URL,
    SIGNUP_URL: Config.SIGNUP_URL,
    PAYMENT_PAGE_URL: Config.PAYMENT_PAGE_URL,
    PRODUCTION_GATEWAY: Config.PRODUCTION_GATEWAY,
    ACL_VERSION: Config.ACL_VERSION,
    ACL_POPUP_SKIP_TIMER: Config.ACL_POPUP_SKIP_TIMER,
    EMAIL_AVA_APP_UPDATE_SUPPORT: Config.EMAIL_AVA_APP_UPDATE_SUPPORT,
    EMAIL_AVA_JOIN_CODE_SUPPORT: Config.EMAIL_AVA_JOIN_CODE_SUPPORT,
    BUNDLE_ID: Config.BUNDLE_ID,
    ENABLE_OFFLINE_CHECK: Config.ENABLE_OFFLINE_CHECK,
    TIMEOUT_MS: 30000,
    GOOGLE_SIGN_IN_IOS_CLIENT_ID: Config.GOOGLE_SIGN_IN_IOS_CLIENT_ID,
}